### ISSUE TITLE
fontawesome 5 free/pro

### ISSUE THREAD

**Issue by Lobster1956** [DirkPersky/typo3-rte-ckeditor-fontawesome#1]
Would this extension gets support for the upcoming version 5 of fontawesome ???

**Comment by DirkPersky** [comment]
Yeah i plan to update it for the FA5 free.

If the FA5 is final and i get some space  to do it ;)

**Comment by DirkPersky** [comment]
Hi @Lobster1956,

i created a beta relase on Github with the first Integration of [FA5](https://fontawesome.com/)

When i move the Version to stable i switch [FA5](https://fontawesome.com/) as the default CKE  selection.

greetings
Dirk
