### ISSUE TITLE
Option to select FontAwesome subversion 

### ISSUE THREAD

**Issue by jpmschuler** [DirkPersky/typo3-rte-ckeditor-fontawesome#10]
Currently the version of FontAwesome used is hardcoded in the css and js files of the extension. However if FontAwesome is self-hosted, it might be, that the template uses a fixed version which might differ from this plugins version. 
E.g. in our scenario we switched already to 5.9.0, although this ext is at 5.8.1 - nevertheless it could be the other way around as a template might stick to an old version.

Thus, I propose to have the version number as a constant (TypoScript? PageTsConfig? Both?). Perhaps the currently used query parameter consisting of extension version could be reused.

**Comment by DirkPersky** [comment]
he, for the FA5-Pro handling and custom config the css file now load more dynamic
