### ISSUE TITLE
New icons in newer version of FontAwsome 5

### ISSUE THREAD

**Issue by agendartobias** [DirkPersky/typo3-rte-ckeditor-fontawesome#13]
There are a lot of new icons in newer version of FontAwsome 5. The problem is that the icons are hardcoded/presetted in file \rte_ckeditor_fontawesome\Resources\Public\JavaScript\Plugins\ckeditor_fa5pro\dialogs\index.html, so if i use newer version fontawsome on FE, backend selection is still limited to old version.

Any idea how can i get newer icons in be?

**Comment by DirkPersky** [comment]
I updated it to FA 5.14.0 and released a new version.
