### ISSUE TITLE
FontaweSome Pro

### ISSUE THREAD

**Issue by alemNative** [DirkPersky/typo3-rte-ckeditor-fontawesome#14]
Hello. There is an Problem with FontAwesome 5 Pro.
I have no Option to use Light version of icons and also the Pro Set is missing (for example no abacus Icon)

i tried with 
- { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/FullFA5Pro.yaml" } 

and 

- { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA5Pro.yaml" }

Same Result its the Free Set

**Comment by DirkPersky** [comment]
I refactored the code, in the pro version should it now be available.
