### ISSUE TITLE
Problems after link change

### ISSUE THREAD

**Issue by rteinze** [DirkPersky/typo3-rte-ckeditor-fontawesome#15]
If there is a linked FA icon and you focus the cursor onto to edit the consisting link then - after "set link" - the icon disappears.

before editing the link:
```
<p><a href="https://www.linkedin.com/in/pers-name-123456/"><i class="fa-2x fa-linkedin fab"> </i></a></p>
```
after editing:
```
<p>&nbsp;</p>
```

**Comment by DirkPersky** [comment]
I tried alot, but this also happens with all alternative CKEditor Font Awesome Plugins.

It seems to be a core problem not specially this plugin ;(

**Comment by rteinze** [comment]
Any suggestion to work around? It makes your extension unusable.

Thanks.

**Comment by DirkPersky** [comment]
No sorry :(

it looks like a core problem of the CKEditor.
