### ISSUE TITLE
Icons are been kicked out of the RTE after save

### ISSUE THREAD

**Issue by lutzeckelmann** [DirkPersky/typo3-rte-ckeditor-fontawesome#20]
I have imported the Icons to my own preset, I can add Icons, but when I save the Content Element only the i-tag are left. The class and aria-hidden tags are gone.
I have done everything like it is describted in the documentation.

**Comment by DirkPersky** [comment]
he, importend is that the 
```
// /Configuration/RTE/PluginFA5.yaml

extraAllowedContent:
    - i(*)[*]
    - span(*)[*]
    - em(*)[*]
```

are present and will not be overwritten.
