### ISSUE TITLE
Toolbar icon ist deactivated - js console error

### ISSUE THREAD

**Issue by blueamerican** [DirkPersky/typo3-rte-ckeditor-fontawesome#21]
TYPO3 9.5.21
typo3-rte-ckeditor-fontawesome 10.2.0

Custom config:
imports:
    - { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA5.yaml" }
toolbarGroups:
    - { name: tools, groups: [ table, specialchar, ckeditor_fa5 ] }
    
 The toolbar icon ist deactivated, see screen.

![Bildschirmfoto 2021-06-09 um 06 48 01](https://user-images.githubusercontent.com/5647051/121295423-5690c800-c8ef-11eb-9ee2-e2d2924be9c5.png)
 
 In the js console there is a js error in ckeditor.js, 
` Uncaught TypeError: e is undefined`
 see screen:

![Bildschirmfoto 2021-06-09 um 06 52 00](https://user-images.githubusercontent.com/5647051/121295449-5e506c80-c8ef-11eb-9772-f414eb57300e.png)

**Comment by DirkPersky** [comment]
he, can u send me your complete Config.
Because that's config shouldn't work anyway.

**Comment by blueamerican** [comment]
[Uploading CsPresets_.yaml.zip…]()
