### ISSUE TITLE
Update to fontawesome 6

### ISSUE THREAD

**Issue by Patta** [DirkPersky/typo3-rte-ckeditor-fontawesome#24]
A release with support for fontawesome 6.0.0 (https://fontawesome.com/changelog/latest) would be great. Thanks

**Comment by Patta** [comment]
@DirkPersky Thanks for the fast release! In my opinion the fontawesome icon related styles in `Resources/Public/JavaScript/Plugins/ckeditor_fa6/css/ckeditor-fa.css` (all .fab, .far, .fas) can be removed, because they are overwritten by the fontawesome stylesheet added in `plugin.js` with `editor.addContentsCss('https://use.fontawesome.com/releases/v6.0.0/css/all.css');`

**Comment by DirkPersky** [comment]
@Patta that absolutely true, thank for the hint.
