### ISSUE TITLE
Update to fontawesome 6.1

### ISSUE THREAD

**Issue by Patta** [DirkPersky/typo3-rte-ckeditor-fontawesome#25]
Support for fontawesome 6.1 (https://fontawesome.com/v6/docs/changelog/) would be great. Thanks again !

**Comment by madeinnature** [comment]
Hi, 
thx a lot, great Extension!
Is an update to the FA6-Pro version planned?

**Comment by DirkPersky** [comment]
@madeinnature 
if i have some more freetime sure.
