### ISSUE TITLE
Differing dependency declarations

### ISSUE THREAD

**Issue by dominikdoerr** [DirkPersky/typo3-rte-ckeditor-fontawesome#26]
ext_emconf.php and composer.json declare different dependencies. Also the dependency on rte-ckeditor is missing in the composer.json. This leads to different dependencies shown on Packagist and in the TER. As the ext_emconf has been changed more recently, I assume the dependencies there are the more up to date.

Stumbled upon this because I could install the newest version despite using an older TYPO3 Version (9), which is not supported according to the TER (works fine regardless).

Which version constraints are the correct ones? I can provide a PR if you like.

**Comment by DirkPersky** [comment]
Oh yeah the `ext_emconf.php` is the correct.
