### ISSUE TITLE
don't use external css to load icons

### ISSUE THREAD

**Issue by medarob** [DirkPersky/typo3-rte-ckeditor-fontawesome#29]
I noticed that an external `all.css` is used in the backend. If the url to the CSS file is broken, the icons wouldn't show anymore, or?
in https://github.com/DirkPersky/typo3-rte-ckeditor-fontawesome/blob/master/Configuration/RTE/PluginFA5.yaml
```
  config:
    fontAwesome:
      - "https://use.fontawesome.com/releases/v5.15.4/css/all.css"
```
Wouldn't it be better not to use an external ressource but to use a FontAwesome version that comes shipped included with the extension?

**Comment by DirkPersky** [comment]
That's why I use a CDN it shouldn't happen there.
Otherwise all font-sources must be placed in the directory and kept up to date.

However you can use a custom configuration if needed:
https://github.com/DirkPersky/typo3-rte-ckeditor-fontawesome#use-fontawesome-pro-or-custom-config
