### ISSUE TITLE
How to remove a inserted icon from the ckeditor?

### ISSUE THREAD

**Issue by dbruening** [DirkPersky/typo3-rte-ckeditor-fontawesome#3]
Hello,

thank you for the implantation of this plugin!

Is there a way to remove a inserted icon from the ckeditor? I didn't find any way with the keyboard.

I searched for a solution and find something. The main problem is, that it isn't possible to remove a blank tag.  So i tried to add a blank space to the i-tag.

To do so, you have to edit the file "rte_ckeditor_fontawesome\Resources\Public\JavaScript\Plugins\ckeditor_fa\dialogs\ckeditor-fa.js" and add on line 134 the followring code to set the content of the i-tag:
`icon.setText(' ');`

**Comment by DirkPersky** [comment]
Hi @dbruening,

thanks for your suggestion.
You a right it was alltimes a bit tricky.

**Comment by siwa-tkapplmueller** [comment]
Hello,

I think this bug appears again in the current version (10.3.0). When looking for possible solutions I found this issue and checked the JS Files. The code to set the content of the i tag mentioned above is included in none of them.

**Comment by Patta** [comment]
I can confirm that issue also in TYPO3 10.4
