### ISSUE TITLE
Missing file PluginFA4.yaml

### ISSUE THREAD

**Issue by jorejore** [DirkPersky/typo3-rte-ckeditor-fontawesome#30]
Trying to add a text content element leaves the following error in the protocoll, no other problems occur (Typo3 version 10.4.28):

__Core: Error handler (BE): PHP Warning: file_get_contents(.../typo3/typo3conf/ext/rte_ckeditor_fontawesome/Configuration/RTE/PluginFA4.yaml): failed to open stream: No such file or directory in .../typo3/typo3_src-10.4.28/typo3/sysext/core/Classes/Configuration/Loader/YamlFileLoader.php line 110__ 

Thanks

**Comment by DirkPersky** [comment]
Yeah FA4 ist dropped with the 11.5.3 Version.
