### ISSUE TITLE
12 LTS 

### ISSUE THREAD

**Issue by JenHa** [DirkPersky/typo3-rte-ckeditor-fontawesome#37]
Are there any plans for 12LTS compatibility?

**Comment by DirkPersky** [comment]
Yes, if i get some free time.

**Comment by linawolf** [comment]
@DirkPersky could some sponsoring / help speed up the update?

**Comment by DirkPersky** [comment]
No, becouse of this Issue https://forge.typo3.org/issues/100861

**Comment by terminal8-nz** [comment]
Is there an update on this situation? (typo3 issue seems to be fixed, but idk if this fixes your problem too ;))
thanks!

**Comment by DirkPersky** [comment]
AH cool,

i will try to take a look in the next few weeks

**Comment by DirkPersky** [comment]
I upload a Version that based on that fix.

BUT the fix ist not in the current 12.4.6 lets wait for **12.4.7**

**Comment by DirkPersky** [comment]
Release is out for TYPO3 12.4.7
