### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jdinse** [DirkPersky/typo3-rte-ckeditor-fontawesome#4]
Hi! 

I installed this in TYPO3 8.7.13 but can't see any difference in CKeditor. Is it working? How can I use it? Do I have to switch to source-mode and insert code like `<i class="fas fa-address-book"></i>`?

Thanks for help!

**Comment by jdinse** [comment]
Yes, added that as it is shown in your screenshot:

![bildschirmfoto 2018-05-16 um 01 10 05](https://user-images.githubusercontent.com/2094378/40088131-fa0d8ecc-58a5-11e8-9951-30993435daf5.png)

**Comment by DirkPersky** [comment]
you dont get the:
<img src="http://dp-dvelop.de/fileadmin/user_upload/git/screenshot-dp-dvelop.de-2018.05.16-01-20-58.png" />
icon right?

Have you any other CKE Plugin installed?
If not can you give me a account to check that?

I tested it on Typo3 `8.7.12`; `9,1.X` and `9.2.X` and there it works.

**Comment by jdinse** [comment]
No, I don't get this icon. I sent you an email.

**Comment by DirkPersky** [comment]
Is it possible you selected the CKeditor "minimal" layout
`RTE.default.preset = minimal`

There i dont integrated the Plugin.
If you use the `default` or `full` cke-preset it shoud work.

```
TS-Config

RTE.default.preset = default
```

**Comment by jdinse** [comment]
Yes, man, that's it! Thanks!!!!!

We had our own layout here, I have completely forgotten that.

**Comment by jdinse** [comment]
> If you use the default or full cke-preset it shoud work.

BTW, you should mention that in your documentation.

**Comment by DirkPersky** [comment]
yeh i will ;)

**Comment by DirkPersky** [comment]
You can extend your CKE-Layout to and includes this parts

Configuration/RTE/Default.yaml
```
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml" } # Import the image plugin configuration
    - { resource: "EXT:rte_ckeditor_fontawesome/Configuration/RTE/PluginFA5.yaml" }
    .......
```
