### ISSUE TITLE
Version 12.0.0 not installable via composer

### ISSUE THREAD

**Issue by Rinxiao** [DirkPersky/typo3-rte-ckeditor-fontawesome#40]
Thank you so much for the v12 update. I wanted to test the extension but ran into an issue when trying to install it via composer.

TYPO3 Version: 12.4.7
Extension Version: 12.0.0

I receive the following error, when I run the command "composer req dirkpersky/typo3-rte-ckeditor-fontawesome":

> dirkpersky/typo3-rte-ckeditor-fontawesome 12.0.0 requires typo3/cms-core ^10.4.0||^11.5.0||dev-master -> found typo3/cms-core[v10.4.0, ..., v10.4.37, v11.5.0, ..., v11.5.32] but it conflicts with your root composer.json require (^12.4.0).

**Comment by DirkPersky** [comment]
Shoud be fixed with 12.0.1
