### ISSUE TITLE
icon dialog window 404

### ISSUE THREAD

**Issue by HorstBaumann** [DirkPersky/typo3-rte-ckeditor-fontawesome#42]
TYPO3 12.4.7 composer
typo3-rte-ckeditor-fontawesome 12.0.1
php 8.2

fresh installation - when i click the fontawesome icon in the rte, the popup/dialog shows 404.

the requested path is: /typo3conf/ext/rte_ckeditor_fontawesome/Resources/Public/JavaScript/Plugins/ckeditor_fa6/dialogs/index.html
but this path does not exist on a composer typo3...
is there a redirect missing or the path has to be changed ...?

**Comment by DirkPersky** [comment]
same as #41 on working on it.
