### ISSUE TITLE
Installation according to manual – to no avail

### ISSUE THREAD

**Issue by dsg1-wolf** [DirkPersky/typo3-rte-ckeditor-fontawesome#9]
Hi folks!

Running into a weird problem here:
I try to install the FA-add-on v9.5.0 to my TYPO3 v8.7.24, CKEditor v8.7.24.

I manage to get the FA-icon shown in the RTE's menu, even in my custom configuration. It's clickable, I am able to select icons, yet, CKEditor keeps stripping the classes within the i-tag, saving an empty paragraph with an empty, classless i-tag inside.

TYPO3 then renders me an em-tag into the page.

I've looked through a multitude of tutorials and hints, but to no avail.

Funny enough, it won't even work if I use the RTE-templates fullFA4 and fullFA5 that come with the add-on.

Greets and regards,
Tom

**Comment by DirkPersky** [comment]
He try this Issue:
#7 

i hope that help you.

**Comment by dsg1-wolf** [comment]
> He try this Issue:
> #7
> 
> i hope that help you.

Sadly, it won't work.

The yaml is loaded correctly (even though I'm not defining style buttons singularly but via 'basicstyles') and the RTE shows up.
The button is there in the menu, the selection of an icon works like a charm.
It puts elements like this into the RTE:

`<p><i class="whatever icon I choose"> </i></p>`

But on save the icon is being stripped from the content again, leaving only:

`<p> <em> </em> </p>`

I'm really unsure where I might be wrong with one of my config entries. Looking through the files, I thought all necessary settings came with the import of PluginFA5.yaml?
